plugins {
    id 'org.springframework.boot' version '3.4.0' apply false
    id 'io.spring.dependency-management' version '1.1.0'
    id 'java'
    id 'org.liquibase.gradle' version '2.2.0'
    id 'com.diffplug.spotless' version '6.25.0'
}

dependencyManagement {
    imports {
        mavenBom org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
    }
}

repositories {
    mavenCentral()
}

version = project.findProperty("commonLibraryVersion") ?: "1.0.0"

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-aop'
    implementation 'org.springframework.boot:spring-boot-starter-batch'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // Lombook Dependencies
    implementation 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Utils Dependencies
    implementation 'org.mapstruct:mapstruct:1.6.3'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
    implementation 'org.postgresql:postgresql:42.7.2'

    // Liquibase Dependencies
    liquibaseRuntime 'org.liquibase:liquibase-core:4.23.0'
    liquibaseRuntime 'info.picocli:picocli:4.7.4'
    liquibaseRuntime 'org.postgresql:postgresql:42.7.2'
}

liquibase {
    activities {
        main {
            changeLogFile 'src/main/resources/db/changelog/db.changelog-master.yaml'
            classpath 'src/main/resources'
            referenceUrl 'hibernate:spring:com.microservice.boilerplate.model?dialect=org.hibernate.dialect.PostgreSQLDialect'
            url 'jdbc:postgresql://localhost:5433/postgres'
            username 'postgres'
            password 'admin'
            driver 'org.postgresql.Driver'
        }
    }
    runList = "main"
}

tasks.jar {
    archiveBaseName.set('common-library')  // Define o nome do arquivo JAR
}

spotless {
    java {
        target fileTree('.') {
            include '**/*.java'
            exclude '**/build/**', '**/build-*/**'
        }
        toggleOffOn()
        palantirJavaFormat()
        removeUnusedImports()
        trimTrailingWhitespace()
        endWithNewline()
    }
}