name: Publish Boilerplate Package in Maven Central Repository

on:
  push:
    branches:
      - develop
      - release
      - main

jobs:

  release:
    runs-on: ubuntu-latest
    outputs:
      module_versions: ${{ steps.set-versions.outputs.module_versions }}
    permissions:
      pull-requests: write
      contents: write
      actions: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Garante que todo o histórico do repositório seja obtido

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm init -y
          npm install
          npm install -g lerna
          npm install --save-dev commitizen standard-version cz-conventional-changelog

      - name: Config Git Identity
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Generate package.json for each module
        run: |
          for dir in modules/*/; do
            MODULE_NAME=$(basename "$dir")
            echo "Creating package.json for $MODULE_NAME"
            echo "{
              \"name\": \"$MODULE_NAME\",
              \"version\": \"0.0.0\",
              \"private\": true
            }" > "$dir/package.json"
          done

      - name: Verify package.json files
        run: find modules -name "package.json" -exec cat {} \;

      - name: Debug Lerna List
        run: |
          lerna clean --yes
          lerna ls

      - name: Determine Versioning Strategy
        id: versioning
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "VERSION_COMMAND=lerna version --yes --no-push --conventional-prerelease --preid beta" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/release" ]]; then
            echo "VERSION_COMMAND=lerna version --yes --no-push --conventional-prerelease --preid rc" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "VERSION_COMMAND=lerna version --yes --no-push --conventional-graduate" >> $GITHUB_ENV
          fi
      

      - name: Run Lerna Versioning
        run: |
          $VERSION_COMMAND
          echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Push Changes
        run: |
          git push origin --follow-tags

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          server-id: github

      - name: List Changed Modules
        run: |
          echo "Checking for changed modules..."
          CHANGED_MODULES=$(lerna changed --json | jq -r '.[].name')
          if [ -z "$CHANGED_MODULES" ]; then
            echo "No modules changed. Exiting."
            exit 0
          else
            echo "Changed modules: $CHANGED_MODULES"
          fi
          echo "CHANGED_MODULES=$CHANGED_MODULES" >> $GITHUB_ENV

      - name: Publish Changed Modules with Gradle
        run: |
          for module in $CHANGED_MODULES; do
            if [ -d "modules/$module" ]; then
              echo "Publishing $module with version $VERSION"
              cd modules/$module
              ./gradlew publish -P${module}Version=$VERSION
              cd -
            fi
          done